### ISSUE TITLE
Newsfeed mit Tags durchsuchen

### ISSUE THREAD

**Issue by twilleit** [sweIhm/sweiproject-tg2b-1#2]
Als Nutzer will ich den Newsfeed mithilfe von Tags durchsuchen, um schnell für mich relevante Beiträge zu finden.

**Comment by Nina2244** [comment]
Backend soweit vorbereitet.
Abzufragende Tags mit URL-Parameter umgesetzt 
=> Abfrage unter: /activity/searchid?1=<abzufragenderTag1>&2=<abzufragenderTag2> ...

- Es können beliebig viele Tags abgefragt werden.
- Es gibt kein Problem wenn ein Tag doppelt abgefragt wird.
