### ISSUE TITLE
Newsfeed als Gast einsehen

### ISSUE THREAD

**Issue by lukaskirner** [sweIhm/sweiproject-tg2b-1#34]
Als Gast will ich den Newsfeed einsehen um alle internationalen Aktivitäten, Projekte , Angebote und Gesuche zu sehen.

**Comment by lukaskirner** [comment]
Funktioniert soweit bloß das momentan keine chronologische Reihenfolge herrsch. Eventuell kann man das json schon so erstellen das dies der Fall ist

**Comment by Nina2244** [comment]
Ich habe das noch mal getestet. Es kommt bei mir in der richtigen Reinfolge an also das mit ID 1 als erstes und dann das mit zwei und so weiter. Du müsstest diese halt umdrehen also das mit der höchsten ID muss halt das sein was als oberstes angezeigt wird.
